### ISSUE TITLE
Python keyword arguments disagree with docs

### ISSUE THREAD

**Issue by siboles** [SimpleITK/SimpleITK#466]
This is a common issue I encounter. The latest occurrence (produced below) came when I updated from 1.0.0 to 1.1.0.

```
import SimpleITK as sitk

img = sitk.Image(3,3, sitk.sitkFloat32)
g = sitk.DiscreteGaussian(img, variance=(1.0,1.0))

```
TypeError: DiscreteGaussian() got an unexpected keyword argument 'variance'

According to the docs, this procedural interface can receive variance as either a positional or keyword argument. However in version 1.1.0, only the positional argument works. As I said, I've encountered these inconsistencies in multiple procedural interfaces, so it may be worth looking into some (additional) testing of positional argument vs keyword argument support for classes that have procedural interfaces.

Best,
Scott

**Comment by blowekamp** [comment]
This is an unfortunate limitation of SWIG currently.

The `DiscreteGaussian` procedure is a overloaded in C++ with two signatures. SWIG can not handle keyword arguments with overloaded methods. The value only arguments still work, and of course the verbose object oriented does as well.

The following are the two current signatures:
```
Image DiscreteGaussian ( const Image& image1,
                                            double variance,
                                             unsigned int maximumKernelWidth = 32u,
                                             double maximumError =  0.01,
                                             bool useImageSpacing = true );
Image DiscreteGaussian ( const Image& image1,
                                             const std::vector<double> & variance = std::vector<double>(3,1.0),
                                             unsigned int maximumKernelWidth = 32u,
                                             const std::vector<double> & maximumError = std::vector<double>(3, 0.01),
                                             bool useImageSpacing = true );
```

I had a discussion about this SWIG issue on the mailing list some time ago. I'll bring it back up as an issue/feature request and link it back here.

**Comment by siboles** [comment]
Thanks for the quick reply. My C++ is weak but in the meantime, would it be good practice to always assign the argument in all overloads i.e.
```
Image DiscreteGaussian ( const Image& image1,
                                            double variance = 1.0,
                                             unsigned int maximumKernelWidth = 32u,
                                             double maximumError =  0.01,
                                             bool useImageSpacing = true );
```
Not sure if this would avoid the wrapping limitation.

**Comment by blowekamp** [comment]
This is only a problem for a few Python procedures called by keyword arguments. For all other wrapped languages, and C++ the second argument is used to determine which overloaded procedure to call. If the second parameter is specified as a scalar the first signature is called, otherwise the second signature is used, including what there is no second parameter. If both signatures has default second parameters, then a call with no second parameter would be ambiguous.
