### ISSUE TITLE
unexpected keyword argument in procedural InvertDisplacementField

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#2425]
Following code works with SimpleITK version 2.5.2 but generates the following error in 3.0.0 `TypeError: InvertDisplacementField() got an unexpected keyword argument 'maximumNumberOfIterations'`
```
import SimpleITK as sitk

displacement_image = sitk.Image([512, 512], sitk.sitkVectorFloat64, 2)
sitk.InvertDisplacementField(
    displacement_image,
    maximumNumberOfIterations=20,
    maxErrorToleranceThreshold=0.01,
    meanErrorToleranceThreshold=0.0001,
    enforceBoundaryCondition=True,
)
```
